services:
  jellyfin-discord-webhook:
    build: .
    container_name: jellyfin-discord-webhook
    ports:
      - "8080:8080"
    volumes:
      # Mount host directories to container, with fallback to container defaults
      - ./config:/app/config:rw
      - ./templates:/app/templates:rw
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    environment:
      - JELLYFIN_SERVER_URL=${JELLYFIN_SERVER_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_USER_ID=${JELLYFIN_USER_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DISCORD_WEBHOOK_URL_MOVIES=${DISCORD_WEBHOOK_URL_MOVIES:-}
      - DISCORD_WEBHOOK_URL_TV=${DISCORD_WEBHOOK_URL_TV:-}
      - DISCORD_WEBHOOK_URL_MUSIC=${DISCORD_WEBHOOK_URL_MUSIC:-}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - jellyfin-webhook-network

networks:
  jellyfin-webhook-network:
    driver: bridge